create table car (
  id               integer generated by default as identity,
  amount           integer,
  brand            varchar(255),
  color            varchar(255),
  doors_amount     smallint,
  drive_type       integer,
  engine_type      integer,
  img_id           integer,
  mileage          bigint,
  model            varchar(255),
  passenger_amount smallint,
  transport_type   integer,
  year             integer,
  primary key (id)
)