create table user (
  id       integer generated by default as identity,
  active   integer not null,
  balance  decimal(19, 2),
  email    varchar(255),
  password varchar(255),
  role     varchar(255),
  token    varchar(255),
  primary key (id)
)
--
